apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zentinel

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - poddisruptionbudget.yaml

commonLabels:
  app.kubernetes.io/part-of: zentinel
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/zentinelproxy/zentinel-agent-waf
    newTag: "0.9.0"
